contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: Reach out to the VEG team
    url: https://github.com/veg/CAPHEINE/issues
    about: If you have questions about the pipeline, please create an issue here
